"""create movies table

Revision ID: 1f210f0285c8
Revises: 
Create Date: 2026-05-17 20:04:23.515289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f210f0285c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('imdb_rating', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('rotten_tomatoes', sa.Integer(), nullable=True),
    sa.Column('my_rating', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('trailer_url', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cast', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
